language: perl
perl:
  - "5.26.0"
  - "5.24.2"
  - "5.24.1"
  - "5.24.0"
  - "5.22.0"
  - "5.20.3"
  - "5.20.2"
  - "5.20.1"
  - "5.20.0"
  - "5.18.2"
  - "5.18.1"
  - "5.18.0"
  - "5.16.2"
  - "5.16.1"
  - "5.16.0"
  - "5.14.4"
  - "5.14.3"
  - "5.14.2"
  - "5.14.2"
  - "5.14.0"
  - "5.12.5"
  - "5.12.4"
  - "5.12.3"
  - "5.12.2"
  - "5.12.1"
  - "5.12.0"
  - "5.10.1"
  - "5.10.0"

notifications:
    email:
    recipients:
        - andy@petdance.com
        - rob@hoelz.ro
    on_success: change
    on_failure: always

install: "cpanm File::Next && cpanm Pod::Perldoc && cpanm --notest IO::Pty Test::Pod"
script:  "perl Makefile.PL && make fulltest"
