language: perl
perl:
  - "dev"
  - "5.24"
  - "5.20"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
notifications:
install: "cpanm File::Next && cpanm --notest IO::Pty Test::Pod"
script:  "perl Makefile.PL && make fulltest"
email:
  recipients:
    - andy@petdance.com
    - rob@hoelz.ro
  on_success: change
  on_failure: always
